name: Learn Github Packaging
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Packaging citylocations for release!

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Runs database migrations on the Django app
      - name: Run migrations
        run: python manage.py migrate

      # Run all tests with verbose flag
      - name: Run all tests
        run: pytest -v
